### ISSUE TITLE
TOFIX: crashes during samplers creation on AMD GCN

### ISSUE THREAD

**Issue by steaklive** [steaklive/DXR-Sandbox-GI#6]
some samplers are crashing on integrated vega 8

**Comment by StRaToX123** [comment]
The root signatures were failing to create on my r9 fury (GCN architecture) as well.
This went away if the samplers get initialized to their default values first such as :
D3D12_SAMPLER_DESC sampler = {};

**Comment by steaklive** [comment]
@StRaToX123 nice catch! Although this repo is gathering dust, i actually noticed a similar behaviour in another project on the same architecture (GCN), even on another platform (console). The solution was to initialize the samplers properly, too.
